---
- name: ensure root .ssh directory exists
  become: true
  file:
    path: /root/.ssh
    state: directory
    owner: root
    group: root
    mode: 0700

- name: install authorized keys
  become: true
  authorized_key:
    user: root
    key: "{{ '\n'.join(root_authorized_keys) }}"
    exclusive: true
  when: root_authorized_keys is defined
